modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="orfadditions"
version="1.0"
displayName="OrfAdditions"
logoFile="logo.png"
credits="Forge Project"
authors="Orf1"
description='''OrfAdditions adds a few intresting changes to the game.'''
[[dependencies.orfadditions]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.orfadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
